/**
 * Learning Scheduler - Phase 9.7.1
 * جدولة التعلّم الذاتي التلقائية
 * 
 * يشغل دورة التعلّم كل 6 ساعات تلقائياً
 * يُنشئ تقارير أسبوعية وشهرية
 */

import { learningEngine } from './autonomous-learning-engine';
import { actionGenerator } from './action-generator';
import { learningReporter } from './learning-reporter';

/**
 * Learning Scheduler Class
 */
export class LearningScheduler {
  private learningInterval: NodeJS.Timeout | null = null;
  private weeklyReportInterval: NodeJS.Timeout | null = null;
  private monthlyReportInterval: NodeJS.Timeout | null = null;
  
  private isRunning: boolean = false;
  
  // Configuration
  private config = {
    learningCycleHours: 6,
    weeklyReportDay: 1, // Monday
    monthlyReportDay: 1, // First day of month
    autoGenerateDecisions: true,
    lookbackDays: 7
  };

  constructor() {
    console.log('[Learning Scheduler] Initialized');
  }

  /**
   * Start the scheduler
   */
  start(): void {
    if (this.isRunning) {
      console.log('[Learning Scheduler] Already running');
      return;
    }

    this.isRunning = true;
    console.log('[Learning Scheduler] 🚀 Starting autonomous learning scheduler...');
    
    // Schedule learning cycles every 6 hours
    const learningIntervalMs = this.config.learningCycleHours * 60 * 60 * 1000;
    this.learningInterval = setInterval(() => {
      this.runLearningCycle().catch(error => {
        console.error('[Learning Scheduler] Learning cycle error:', error);
      });
    }, learningIntervalMs);
    
    // Schedule weekly reports (every Monday at 00:00)
    this.scheduleWeeklyReport();
    
    // Schedule monthly reports (first day of month at 00:00)
    this.scheduleMonthlyReport();
    
    // Run initial learning cycle
    setTimeout(() => {
      this.runLearningCycle().catch(error => {
        console.error('[Learning Scheduler] Initial learning cycle error:', error);
      });
    }, 5000); // 5 seconds after start
    
    console.log(`[Learning Scheduler] ✅ Scheduled to run every ${this.config.learningCycleHours} hours`);
    console.log('[Learning Scheduler] ✅ Weekly reports scheduled (Mondays)');
    console.log('[Learning Scheduler] ✅ Monthly reports scheduled (1st of month)');
  }

  /**
   * Stop the scheduler
   */
  stop(): void {
    if (!this.isRunning) {
      console.log('[Learning Scheduler] Not running');
      return;
    }

    if (this.learningInterval) {
      clearInterval(this.learningInterval);
      this.learningInterval = null;
    }

    if (this.weeklyReportInterval) {
      clearInterval(this.weeklyReportInterval);
      this.weeklyReportInterval = null;
    }

    if (this.monthlyReportInterval) {
      clearInterval(this.monthlyReportInterval);
      this.monthlyReportInterval = null;
    }

    this.isRunning = false;
    console.log('[Learning Scheduler] ⏹️  Stopped');
  }

  /**
   * Run learning cycle
   */
  private async runLearningCycle(): Promise<void> {
    console.log('\n' + '='.repeat(60));
    console.log('[Learning Scheduler] 🧠 Running scheduled learning cycle...');
    console.log('='.repeat(60));
    
    const startTime = Date.now();
    
    try {
      // 1. Run learning engine
      const insights = await learningEngine.runLearningCycle({
        lookbackDays: this.config.lookbackDays
      });
      
      console.log(`[Learning Scheduler] Generated ${insights.length} insights`);
      
      // 2. Auto-generate decisions if enabled
      if (this.config.autoGenerateDecisions && insights.length > 0) {
        const decisions = await actionGenerator.generateBatchDecisions(insights);
        console.log(`[Learning Scheduler] Generated ${decisions.length} decisions`);
        
        // Mark decisions as sent (in real deployment, they would be sent to nodes)
        for (const decision of decisions) {
          await actionGenerator.updateDecisionStatus(decision.decisionId, 'sent');
        }
      }
      
      const duration = Date.now() - startTime;
      console.log(`[Learning Scheduler] ✅ Learning cycle completed in ${duration}ms`);
      console.log('='.repeat(60) + '\n');
      
    } catch (error: any) {
      console.error('[Learning Scheduler] ❌ Learning cycle failed:', error.message);
      console.error('='.repeat(60) + '\n');
    }
  }

  /**
   * Schedule weekly report generation
   */
  private scheduleWeeklyReport(): void {
    // Calculate time until next Monday 00:00
    const now = new Date();
    const daysUntilMonday = (1 - now.getDay() + 7) % 7 || 7;
    const nextMonday = new Date(now);
    nextMonday.setDate(now.getDate() + daysUntilMonday);
    nextMonday.setHours(0, 0, 0, 0);
    
    const msUntilMonday = nextMonday.getTime() - now.getTime();
    
    // Schedule first report
    setTimeout(() => {
      this.generateWeeklyReport();
      
      // Then schedule weekly recurring
      this.weeklyReportInterval = setInterval(() => {
        this.generateWeeklyReport();
      }, 7 * 24 * 60 * 60 * 1000); // Every 7 days
      
    }, msUntilMonday);
    
    console.log(`[Learning Scheduler] Next weekly report: ${nextMonday.toISOString()}`);
  }

  /**
   * Schedule monthly report generation
   */
  private scheduleMonthlyReport(): void {
    // Calculate time until first day of next month 00:00
    const now = new Date();
    const nextMonth = new Date(now.getFullYear(), now.getMonth() + 1, 1, 0, 0, 0, 0);
    const msUntilNextMonth = nextMonth.getTime() - now.getTime();
    
    // Schedule first report
    setTimeout(() => {
      this.generateMonthlyReport();
      
      // Then schedule monthly recurring
      this.monthlyReportInterval = setInterval(() => {
        this.generateMonthlyReport();
      }, 30 * 24 * 60 * 60 * 1000); // Approximately every 30 days
      
    }, msUntilNextMonth);
    
    console.log(`[Learning Scheduler] Next monthly report: ${nextMonth.toISOString()}`);
  }

  /**
   * Generate weekly report
   */
  private async generateWeeklyReport(): Promise<void> {
    console.log('\n' + '='.repeat(60));
    console.log('[Learning Scheduler] 📊 Generating weekly learning report...');
    console.log('='.repeat(60));
    
    try {
      const report = await learningReporter.generateWeeklyReport();
      
      console.log('[Learning Scheduler] ✅ Weekly report generated:');
      console.log(`  Report ID: ${report.reportId}`);
      console.log(`  Total Decisions: ${report.summary.totalDecisions}`);
      console.log(`  Avg Confidence: ${report.summary.avgConfidence.toFixed(2)}`);
      console.log(`  Avg Success Rate: ${report.summary.avgSuccessRate.toFixed(2)}`);
      console.log(`  Confidence Growth: ${report.trends.confidenceGrowth.toFixed(1)}%`);
      console.log(`  Learning Velocity: ${report.trends.learningVelocity}`);
      console.log('='.repeat(60) + '\n');
      
    } catch (error: any) {
      console.error('[Learning Scheduler] ❌ Weekly report failed:', error.message);
      console.error('='.repeat(60) + '\n');
    }
  }

  /**
   * Generate monthly report
   */
  private async generateMonthlyReport(): Promise<void> {
    console.log('\n' + '='.repeat(60));
    console.log('[Learning Scheduler] 📊 Generating monthly learning report...');
    console.log('='.repeat(60));
    
    try {
      const report = await learningReporter.generateMonthlyReport();
      
      console.log('[Learning Scheduler] ✅ Monthly report generated:');
      console.log(`  Report ID: ${report.reportId}`);
      console.log(`  Total Decisions: ${report.summary.totalDecisions}`);
      console.log(`  Avg Confidence: ${report.summary.avgConfidence.toFixed(2)}`);
      console.log(`  Avg Success Rate: ${report.summary.avgSuccessRate.toFixed(2)}`);
      console.log(`  Confidence Growth: ${report.trends.confidenceGrowth.toFixed(1)}%`);
      console.log(`  Accuracy Improvement: ${report.trends.accuracyImprovement.toFixed(1)}%`);
      console.log('='.repeat(60) + '\n');
      
    } catch (error: any) {
      console.error('[Learning Scheduler] ❌ Monthly report failed:', error.message);
      console.error('='.repeat(60) + '\n');
    }
  }

  /**
   * Update configuration
   */
  updateConfig(config: Partial<typeof this.config>): void {
    this.config = { ...this.config, ...config };
    console.log('[Learning Scheduler] Configuration updated:', this.config);
    
    // Restart if running to apply new config
    if (this.isRunning) {
      this.stop();
      this.start();
    }
  }

  /**
   * Get current configuration
   */
  getConfig() {
    return { ...this.config };
  }

  /**
   * Get status
   */
  getStatus() {
    return {
      isRunning: this.isRunning,
      config: this.config,
      nextLearningCycle: this.learningInterval ? 'Scheduled' : 'Not scheduled',
      nextWeeklyReport: this.weeklyReportInterval ? 'Scheduled' : 'Not scheduled',
      nextMonthlyReport: this.monthlyReportInterval ? 'Scheduled' : 'Not scheduled'
    };
  }

  /**
   * Manually trigger learning cycle
   */
  async triggerLearningCycle(): Promise<void> {
    console.log('[Learning Scheduler] Manual learning cycle triggered');
    await this.runLearningCycle();
  }

  /**
   * Manually trigger weekly report
   */
  async triggerWeeklyReport(): Promise<void> {
    console.log('[Learning Scheduler] Manual weekly report triggered');
    await this.generateWeeklyReport();
  }

  /**
   * Manually trigger monthly report
   */
  async triggerMonthlyReport(): Promise<void> {
    console.log('[Learning Scheduler] Manual monthly report triggered');
    await this.generateMonthlyReport();
  }
}

// Export singleton instance
export const learningScheduler = new LearningScheduler();

// DISABLED: Auto-start causes infinite loop and memory leak
// Auto-start scheduler on import
// Note: In production, you may want to control this via environment variable
// if (process.env.AUTO_START_LEARNING_SCHEDULER !== 'false') {
//   learningScheduler.start();
// }

console.log('[Learning Scheduler] Module loaded (auto-start DISABLED)');
